version: '3.8'

services:
  onesun-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onesun-app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
      - ./data:/app/data
    restart: unless-stopped
    working_dir: /app/apps/main
    command: ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
